# Generated by Django 5.0.3 on 2024-03-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_customerinformation_delivery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'покупатель', 'verbose_name_plural': 'покупатели'},
        ),
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'доставка', 'verbose_name_plural': 'доставки'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderitems',
            options={'verbose_name': 'предмет заказа', 'verbose_name_plural': 'предметы заказа'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
        migrations.AlterField(
            model_name='customerinformation',
            name='phone',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='baguette',
            field=models.BooleanField(blank=True, null=True, verbose_name='Багет'),
        ),
        migrations.AlterField(
            model_name='product',
            name='count',
            field=models.IntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='product',
            name='creation_year',
            field=models.IntegerField(blank=True, default=0, verbose_name='Год создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='decor',
            field=models.CharField(blank=True, max_length=255, verbose_name='Декор'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Цена со скидкой'),
        ),
        migrations.AlterField(
            model_name='product',
            name='frame',
            field=models.BooleanField(blank=True, null=True, verbose_name='Рамка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='genre',
            field=models.CharField(blank=True, max_length=255, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='product', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(max_length=255, null=True, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='product',
            name='passe_partout',
            field=models.BooleanField(blank=True, null=True, verbose_name='Паспарту'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(max_length=255, null=True, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='product',
            name='technique',
            field=models.CharField(blank=True, max_length=255, verbose_name='Техника'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
