# Generated by Django 5.0.3 on 2024-03-18 17:23

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_category_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.category', verbose_name='Родительская категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=main.models.Category.get_default_pk, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='+', to='main.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='decor',
            field=models.CharField(blank=True, max_length=255, verbose_name='Оформление'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.IntegerField(blank=True, default=0, verbose_name='Цена со скидкой'),
        ),
        migrations.AlterField(
            model_name='product',
            name='frame',
            field=models.BooleanField(blank=True, null=True, verbose_name='Подрамник'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='technique',
            field=models.CharField(max_length=255, verbose_name='Техника'),
        ),
    ]
