# Generated by Django 5.0.2 on 2024-03-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_product_created_at_product_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='nab_chelny_curier_price',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='pickup',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='russia_curier_price',
        ),
        migrations.AddField(
            model_name='delivery',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Стоимость доставки'),
        ),
    ]
